services:
  - type: web
    name: mscs-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: ENABLE_WHISPER
        value: "false"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
